### ISSUE TITLE
Minesweeper moving through the edges

### ISSUE THREAD

**Issue by Stefo0** [panki27/minesweeper#4]
Hi,
Thanks for what you did to bring this game to the Flipper Zero. It’s the best game available till now.

I it possible to allow to jump to the other side of the field every time I go over the edge?
For example, if I'm positioned in the last column on the right and I move to the right, the cursor should appear on the first column on the left, same row.

Flipper Zero is not a touchscreen device so it will make much easier to move within the field.

**Comment by panki27** [comment]
Hi, this is already implemented in the latest release: https://github.com/panki27/minesweeper/releases/tag/v1.2

I also answered your mail regarding this :)

**Comment by Stefo0** [comment]
Thanks!! It works like a charm!
