### ISSUE TITLE
mines are not appearing in row and column of first placement

### ISSUE THREAD

**Issue by mikhatech** [panki27/minesweeper#8]
When starting a game and clicking on a field, no mines appear on the row and column of first placement. This leads to a win strategy of the game: You cklick a random field and click every field in the column and row of the first cklick field. I am a beginner in contributing to open source projects. I will try to resolve this issue.

**Comment by panki27** [comment]
@mikhatech good find! I never noticed this during testing, but now it seems so obvious.

I've identified the bug. Hint: You only need to change 2 characters to fix it 😏

If you need some help contributing, please let me know, I'm happy to help ❤

**Comment by mikhatech** [comment]
I fixed it
